---
title: "Visualize"
output: 
  md_document:
    variant: markdown_github
---

```{r echo=FALSE, message=FALSE}
library(reshape2)
library(plyr)
library(ggplot2)
library(dplyr)
library(data.table)
library(tm)
library(qdap)
library(wordcloud)
library(ggdendro)
library(RColorBrewer)
library(gridExtra)
library(slam)

qdap_clean <- function(x) {
  x <- replace_abbreviation(x)
  x <- replace_contraction(x)
  x <- replace_ordinal(x)
  x <- replace_symbol(x)
  x <- tolower(x)
  return(x)
}

color_palette <-  brewer.pal(12, 'Paired')
reviews <- fread("ScoredReviews.csv", header = TRUE, stringsAsFactors = FALSE)
variables <- colnames(reviews)
variables[2] <- "V2"
names(reviews) <- variables

reviews_with_sentiment <- reviews %>% select(anger, anticipation, disgust, fear,
                                             joy, sadness, surprise, trust,
                                             negative, positive, is_helpful, Id)
melted <- melt(reviews_with_sentiment, id.vars=c("Id", "is_helpful"))
means <- ddply(melted, c("is_helpful", "variable"), summarise, mean=mean(value))
```

```{r echo=FALSE}
ggplot(data = means, aes(x = factor(is_helpful), y = mean)) +
  geom_bar(stat = "identity", position = "dodge", aes(fill = variable)) +
  scale_fill_manual(values = color_palette)
```

```{r echo=FALSE, message=FALSE, results="hide"}
helpful_reviews <- reviews %>% filter(is_helpful == 1)
unhelpful_reviews <- reviews %>% filter(is_helpful == 0)

# Clean text
helpful   <- qdap_clean(helpful_reviews$Text)
unhelpful <- qdap_clean(unhelpful_reviews$Text)

my_stopwords <- c(stopwords('english'))

helpful.corpus <- Corpus(VectorSource(helpful))
helpful.corpus <- tm_map(helpful.corpus, removePunctuation)
helpful.corpus <- tm_map(helpful.corpus, removeWords, my_stopwords)
helpful.dtm <- TermDocumentMatrix(helpful.corpus)
helpful.dtm2 <- removeSparseTerms(helpful.dtm, sparse=0.95)
helpful.df <- as.data.frame(inspect(helpful.dtm2))
helpful.df.scale <- scale(helpful.df)
helpful_d <- dist(helpful.df.scale, method = "euclidean")
helpful_fit <- hclust(helpful_d, method="ward.D")

unhelpful.corpus <- Corpus(VectorSource(unhelpful))
unhelpful.corpus <- tm_map(unhelpful.corpus, removePunctuation)
unhelpful.corpus <- tm_map(unhelpful.corpus, removeWords, my_stopwords)
unhelpful.dtm <- TermDocumentMatrix(unhelpful.corpus)
unhelpful.dtm2 <- removeSparseTerms(unhelpful.dtm, sparse=0.95)
unhelpful.df <- as.data.frame(inspect(unhelpful.dtm2))
unhelpful.df.scale <- scale(unhelpful.df)
unhelpful_d <- dist(unhelpful.df.scale, method = "euclidean")
unhelpful_fit <- hclust(unhelpful_d, method="ward.D")
```

```{r echo=FALSE}
ggdendrogram(helpful_fit, rotate = TRUE) +
  labs(title = "Helpful Reviews")


ggdendrogram(unhelpful_fit, rotate = TRUE) +
  labs(title = "Unhelpful Reviews")
```

```{r echo=FALSE, message=FALSE, results="hide"}
# Remove words
my_stopwords <- c(stopwords('english'), 'amazon', 'like', 'coffee', 'taste', 'food', 'will', 'flavor', 'product', 'one', 'can', 'just', 'good', 'really', 'tea', 'much', 'love', 'also', 'great', 'tried', 'get', 'use', 'time', 'even', 'try', 'now', 'make', 'little', 'buy', 'better', 'well', 'way', 'water', 'cup', 'price', 'made', 'found', 'find', 'first', 'eat', 'dog', 'chocolate', 'box', 'bought', 'bag', 'tastes', 'best', 'used', 'two', 'think', 'thought', 'sweet', 'sugar', 'still', 'know', 'drink', 'dot')
helpful.corpus <- tm_map(helpful.corpus, removeWords, my_stopwords)
unhelpful.corpus <- tm_map(unhelpful.corpus, removeWords, my_stopwords)

# Stem words
helpful.corpus <- tm_map(helpful.corpus, stemDocument)
unhelpful.corpus <- tm_map(unhelpful.corpus, stemDocument)

# Create TDM
helpful.dtm <- TermDocumentMatrix(helpful.corpus)
unhelpful.dtm <- TermDocumentMatrix(unhelpful.corpus)
```

For getting row sums, I am using the `slam` package as it is a much more memory efficient way to do this.

```{r}
# Create matrix
# helpful_matrix   <- as.matrix(helpful.dtm)
# unhelpful_matrix <- as.matrix(unhelpful.dtm)

# Calculate frequency
helpful_frequency   <- slam::row_sums(helpful.dtm, na.rm=T)
unhelpful_frequency <- slam::row_sums(unhelpful.dtm, na.rm=T)
```


```{r echo=FALSE}
# Plot wordcloud

layout(matrix(c(1, 2), nrow=2), heights=c(1, 20))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "Helpful Reviews")
wordcloud(names(helpful_frequency),
          helpful_frequency,
          max.words = 25,
          colors=color_palette)

layout(matrix(c(1, 2), nrow=2), heights=c(1, 20))
par(mar=rep(0, 4))
plot.new()
text(x=0.5, y=0.5, "Unhelpful Reviews")
wordcloud(names(unhelpful_frequency),
          unhelpful_frequency,
          max.words = 25,
          colors=color_palette)
```


In order to arrange the bar plots, I have used the `reorder()` function within the x aesthetics. Seems to be working.

```{r}
helpful_df <- data.frame(word = names(helpful_frequency),
                         count = helpful_frequency) %>%
  arrange(desc(count)) %>%
  top_n(20)
unhelpful_df <- data.frame(word = names(unhelpful_frequency),
                           count = unhelpful_frequency) %>%
  arrange(desc(count)) %>%
  top_n(20)

helpful_word_plot <- ggplot(helpful_df,
                            aes(x = reorder(word, count), y = count)) +
  geom_bar(aes(alpha = count),
           stat="identity",
           fill = color_palette[[1]]) +
  coord_flip() +
  labs(x = NULL, y = "count", title = "Helpful") +
  scale_alpha_continuous(range = c(0.6, 1), guide = FALSE)

unhelpful_word_plot <- ggplot(unhelpful_df,
                              aes(x = reorder(word, count), y = count)) +
  geom_bar(aes(alpha = count),
           stat="identity",
           fill = color_palette[[2]]) +
  coord_flip() +
  labs(x = NULL, y = "count", title = "Unhelpful") +
  scale_alpha_continuous(range = c(0.6, 1), guide = FALSE)

grid.arrange(helpful_word_plot, unhelpful_word_plot, ncol = 2)
```

```{r}
ggplot(reviews %>% filter(word_count < 1000),
       aes(word_count, fill = as.factor(helpful_category))) +
  geom_bar(position = "dodge")
```


```{r echo=FALSE}
ggplot(reviews,
       aes(as.factor(review_category),
           fill = as.factor(helpful_category))) +
  geom_bar(position = "dodge")

ggplot(reviews,
       aes(as.factor(Score),
           fill = as.factor(helpful_category))) +
  geom_bar(position = "dodge")
```

```{r}
ggplot(reviews,
    aes(x = helpful_category,
        y = afinn_sentiment_mean,
        fill = helpful_category)) +
    geom_boxplot() +
    labs(x = "Helpfulness",
         y = "Afinn Sentiment Mean",
         title = "Distribution of Helpfulness Afinn Sentiment") +
    scale_fill_manual(values = color_palette)

ggplot(reviews,
    aes(x = helpful_category,
        y = bing_sentiment_mean,
        fill = helpful_category)) +
    geom_boxplot() +
    labs(x = "Helpfulness",
         y = "Bing Sentiment Mean",
         title = "Distribution of Helpfulness Bing Sentiment") +
    scale_fill_manual(values = color_palette)

ggplot(reviews,
    aes(x = helpful_category,
        y = sentiment_mean,
        fill = helpful_category)) +
    geom_boxplot() +
    labs(x = "Helpfulness",
         y = "Syuzhet Sentiment Mean",
         title = "Distribution of Helpfulness Syuzhet Sentiment") +
    scale_fill_manual(values = color_palette)
```